"""

The conjecture/ package shipped in v2 (ConjectureProposer +
ConjectureVerifier) but had no first-class place in the agent loop —
no Profile advertised it as an action the LLM could take. V6 closes
that with:

  * a ``CONJECTURE_PROPOSE`` ToolKit value
  * a ``ConjectureProposeTool`` in tools_extra.py wrapping the proposer
  * a ``conjecture_driven`` framing in system_prompts.py
  * a ``conjecture_driven`` Profile in PRESETS
  * a YAML template generated by scripts/dump_profile_yamls.py

These tests pin all five surfaces. They use a mock LLM so no real
network calls happen — the test goal is contract verification, not
proof quality.
"""
from __future__ import annotations

import asyncio
from unittest.mock import MagicMock

import pytest

from agent.tools.base import ToolContext
from prover.unified.profiles import (
    PRESETS, Profile, ToolKit, get_profile)
from prover.unified.system_prompts import _FRAMINGS, render_system_prompt
from prover.unified.tool_kits import build_tool_registry
from prover.unified.tools_extra import ConjectureProposeTool

# ─────────────────────────────────────────────────────────────────────
# Fixtures
# ─────────────────────────────────────────────────────────────────────

def _mock_llm_with_lemmas(lemmas: list[str]):
    """Build an LLM mock whose .generate returns the given lemma lines.

    The proposer's regex picks up lines that start with ``lemma`` or
    ``theorem``. Anything else is dropped.
    """
    body = "\n".join(lemmas)
    llm = MagicMock()
    response = MagicMock()
    response.content = body
    llm.generate = MagicMock(return_value=response)
    return llm

@pytest.fixture
def llm_mock():
    """Default mock returning three plausible Lean 4 lemma stubs."""
    return _mock_llm_with_lemmas([
        "lemma helper_one (n : ℕ) : n + 0 = n",
        "lemma helper_two (a b : ℕ) : a + b = b + a",
        "lemma helper_three (n : ℕ) : 0 + n = n",
    ])

# ─────────────────────────────────────────────────────────────────────
# ToolKit enum surface
# ─────────────────────────────────────────────────────────────────────

class TestToolKitEnum:

    def test_conjecture_propose_kit_exists(self):
        assert hasattr(ToolKit, "CONJECTURE_PROPOSE")

    def test_conjecture_propose_kit_value(self):
        assert ToolKit.CONJECTURE_PROPOSE.value == "conjecture_propose"

    def test_kit_value_unique(self):
        # Pin the new kit doesn't collide with any other.
        values = [k.value for k in ToolKit]
        assert len(values) == len(set(values))

# ─────────────────────────────────────────────────────────────────────
# Profile in PRESETS
# ─────────────────────────────────────────────────────────────────────

class TestPresetRegistration:

    def test_conjecture_driven_in_presets(self):
        assert "conjecture_driven" in PRESETS

    def test_get_profile_returns_conjecture_driven(self):
        prof = get_profile("conjecture_driven")
        assert isinstance(prof, Profile)
        assert prof.name == "conjecture_driven"

    def test_profile_includes_conjecture_propose_tool(self):
        prof = get_profile("conjecture_driven")
        assert ToolKit.CONJECTURE_PROPOSE in prof.tools

    def test_profile_includes_lean_verify(self):
        # Helpers must be verifiable; the profile must include the
        # verification tool.
        prof = get_profile("conjecture_driven")
        assert ToolKit.LEAN_VERIFY in prof.tools

    def test_profile_max_turns_reasonable(self):
        prof = get_profile("conjecture_driven")
        # Conjecturing + helper-proof + main-proof = at least a few
        # turns, but bounded.
        assert 5 <= prof.max_turns <= 50

    def test_profile_uses_conjecture_driven_framing(self):
        prof = get_profile("conjecture_driven")
        assert prof.framing == "conjecture_driven"

    def test_profile_no_external_search(self):
        # The profile is single-loop — search.kind == "none".
        prof = get_profile("conjecture_driven")
        assert prof.search.kind == "none"

# ─────────────────────────────────────────────────────────────────────
# Framing surface
# ─────────────────────────────────────────────────────────────────────

class TestFraming:

    def test_conjecture_driven_framing_exists(self):
        assert "conjecture_driven" in _FRAMINGS

    def test_render_system_prompt_for_conjecture_driven(self):
        rendered = render_system_prompt("conjecture_driven")
        assert isinstance(rendered, str)
        assert len(rendered) > 100
        # The framing should mention the workflow phases
        assert "conjecture_propose" in rendered.lower() or \
               "auxiliary" in rendered.lower()

    def test_framing_does_not_advise_sorry(self):
        # Hard contract: no framing should encourage sorry/admit.
        rendered = render_system_prompt("conjecture_driven")
        # The framing may MENTION 'sorry' to forbid it, but it should
        # forbid it explicitly.
        if "sorry" in rendered.lower():
            assert "do not use" in rendered.lower() or \
                   "no `sorry`" in rendered.lower() or \
                   "do NOT use" in rendered

# ─────────────────────────────────────────────────────────────────────
# Tool registry build
# ─────────────────────────────────────────────────────────────────────

class TestToolRegistryBuild:

    def test_build_registry_includes_conjecture_tool(self, llm_mock):
        prof = get_profile("conjecture_driven")
        registry = build_tool_registry(prof, llm=llm_mock)
        # The conjecture tool's name as exposed to the LLM
        assert registry.get("conjecture_propose") is not None

    def test_build_registry_without_llm_still_succeeds(self):
        # A registry can be built without an LLM — execute() will
        # error at call time. This matches the contract for every
        # other tool (e.g. infra tools build with no backend, error
        # at execute time).
        prof = get_profile("conjecture_driven")
        registry = build_tool_registry(prof)
        assert registry.get("conjecture_propose") is not None

    def test_built_tool_is_correct_type(self, llm_mock):
        prof = get_profile("conjecture_driven")
        registry = build_tool_registry(prof, llm=llm_mock)
        tool = registry.get("conjecture_propose")
        assert isinstance(tool, ConjectureProposeTool)

    def test_built_tool_has_llm_bound_when_passed(self, llm_mock):
        prof = get_profile("conjecture_driven")
        registry = build_tool_registry(prof, llm=llm_mock)
        tool = registry.get("conjecture_propose")
        assert tool._llm is llm_mock

# ─────────────────────────────────────────────────────────────────────
# Tool execution — happy paths
# ─────────────────────────────────────────────────────────────────────

def _run(coro):
    return asyncio.run(coro)

class TestToolExecuteHappyPath:

    def test_execute_returns_proposed_lemmas(self, llm_mock):
        tool = ConjectureProposeTool(llm=llm_mock)
        ctx = ToolContext()
        result = _run(tool.execute(
            {"theorem": "theorem t (n : ℕ) : n + 0 = n", "n": 3},
            ctx,
        ))
        assert not result.is_error
        import json
        payload = json.loads(result.content)
        assert isinstance(payload, list)
        assert len(payload) <= 3
        for item in payload:
            assert "statement" in item

    def test_execute_extracts_only_lemma_lines(self):
        # The proposer's regex strips lines that don't start with
        # ``lemma`` or ``theorem``. Pin that behaviour through the tool.

        # 了平凡命题 (e.g. a = a 反身), 测试用例必须避开这条。
        llm = _mock_llm_with_lemmas([
            "Some preamble",
            "lemma good_one (n : ℕ) : n + 0 = n",
            "Comment in the middle",
            "lemma good_two (k : ℕ) : k + 1 > k",
            "More commentary",
        ])
        tool = ConjectureProposeTool(llm=llm)
        ctx = ToolContext()
        result = _run(tool.execute(
            {"theorem": "theorem t (n : ℕ) : n + 0 = n", "n": 10}, ctx))
        assert not result.is_error
        import json
        payload = json.loads(result.content)
        # The proposer asks for n*2 = 20 candidates, gets at most 2 from
        # the mock (only two lemma-prefixed lines), and returns up to n.
        assert all("lemma" in item["statement"] for item in payload)
        statements = [item["statement"] for item in payload]
        assert any("good_one" in s for s in statements)
        assert any("good_two" in s for s in statements)

    def test_execute_clamps_n_to_max(self, llm_mock):
        # n=999 must not blow up — the tool should clamp.
        tool = ConjectureProposeTool(llm=llm_mock)
        ctx = ToolContext()
        result = _run(tool.execute(
            {"theorem": "theorem t : True", "n": 999}, ctx))
        assert not result.is_error

    def test_execute_clamps_n_to_min(self, llm_mock):
        # n=0 must not blow up — the tool should clamp upwards.
        tool = ConjectureProposeTool(llm=llm_mock)
        ctx = ToolContext()
        result = _run(tool.execute(
            {"theorem": "theorem t : True", "n": 0}, ctx))
        assert not result.is_error

    def test_execute_with_existing_lemmas(self, llm_mock):
        # existing_lemmas should be passed through to the proposer
        # without crashing.
        tool = ConjectureProposeTool(llm=llm_mock)
        ctx = ToolContext()
        result = _run(tool.execute({
            "theorem": "theorem t : True",
            "existing_lemmas": ["lemma already_have : True"],
        }, ctx))
        assert not result.is_error

# ─────────────────────────────────────────────────────────────────────
# Tool execution — error paths
# ─────────────────────────────────────────────────────────────────────

class TestToolExecuteErrors:

    def test_execute_no_llm_returns_structured_error(self):
        # No LLM at construction, no llm in ctx.shared_state, no
        # legacy ctx.llm.
        tool = ConjectureProposeTool(llm=None)
        ctx = ToolContext()
        result = _run(tool.execute(
            {"theorem": "theorem t : True"}, ctx))
        assert result.is_error
        assert "no LLM" in result.content.lower() or \
               "llm" in result.content.lower()

    def test_execute_empty_theorem_returns_error(self, llm_mock):
        tool = ConjectureProposeTool(llm=llm_mock)
        ctx = ToolContext()
        result = _run(tool.execute({"theorem": "  "}, ctx))
        assert result.is_error
        assert "empty" in result.content.lower() or \
               "theorem" in result.content.lower()

    def test_execute_proposer_raising_returns_structured_error(self):
        # An LLM whose generate() raises must not crash the tool.
        llm = MagicMock()
        llm.generate = MagicMock(side_effect=RuntimeError("boom"))
        tool = ConjectureProposeTool(llm=llm)
        ctx = ToolContext()
        result = _run(tool.execute(
            {"theorem": "theorem t : True"}, ctx))
        assert result.is_error
        assert "proposer failed" in result.content.lower() or \
               "boom" in result.content.lower()

# ─────────────────────────────────────────────────────────────────────
# Tool execution — LLM lookup priority
# ─────────────────────────────────────────────────────────────────────

class TestLLMLookupPriority:

    def test_construction_llm_wins_over_shared_state(self):
        # Tool-bound LLM should win even if shared_state has a different
        # one — predictable provenance.
        bound_llm = _mock_llm_with_lemmas(["lemma bound : True"])
        ctx_llm = _mock_llm_with_lemmas(["lemma from_ctx : True"])
        tool = ConjectureProposeTool(llm=bound_llm)
        ctx = ToolContext()
        ctx.shared_state["llm"] = ctx_llm
        _run(tool.execute({"theorem": "theorem t : True"}, ctx))
        bound_llm.generate.assert_called()
        ctx_llm.generate.assert_not_called()

    def test_shared_state_llm_used_when_no_construction_llm(self):
        ctx_llm = _mock_llm_with_lemmas(["lemma from_ctx : True"])
        tool = ConjectureProposeTool(llm=None)
        ctx = ToolContext()
        ctx.shared_state["llm"] = ctx_llm
        result = _run(tool.execute({"theorem": "theorem t : True"}, ctx))
        assert not result.is_error
        ctx_llm.generate.assert_called()

    def test_legacy_ctx_llm_attribute_works(self):
        # ctx.llm as an attribute (not in shared_state) — back-compat
        # for non-standard runtimes.
        ctx_llm = _mock_llm_with_lemmas(["lemma legacy : True"])
        tool = ConjectureProposeTool(llm=None)
        ctx = ToolContext()
        # ToolContext is a dataclass; attach via setattr
        ctx.llm = ctx_llm  # type: ignore[attr-defined]
        result = _run(tool.execute({"theorem": "theorem t : True"}, ctx))
        assert not result.is_error
        ctx_llm.generate.assert_called()

# ─────────────────────────────────────────────────────────────────────
# Tool schema surface
# ─────────────────────────────────────────────────────────────────────

class TestToolSchema:

    def test_tool_has_name(self):
        tool = ConjectureProposeTool()
        assert tool.name == "conjecture_propose"

    def test_tool_has_input_schema(self):
        tool = ConjectureProposeTool()
        schema = tool.input_schema
        assert schema["type"] == "object"
        assert "theorem" in schema["properties"]
        assert "theorem" in schema["required"]

    def test_tool_description_mentions_purpose(self):
        tool = ConjectureProposeTool()
        d = tool.description.lower()
        # Should mention "auxiliary" or "lemma" or "conjecture"
        assert any(w in d for w in
                   ("auxiliary", "lemma", "conjecture"))

# ─────────────────────────────────────────────────────────────────────
# YAML round-trip — leverages V5's per-file parameterised tests
# (test_yaml_profile_templates.py) but pin two more contracts here.
# ─────────────────────────────────────────────────────────────────────

class TestYAMLPresence:

    def test_conjecture_driven_yaml_file_exists(self, tmp_path):
        from pathlib import Path
        repo = Path(__file__).resolve().parent.parent
        yaml_path = repo / "config" / "profiles" / "conjecture_driven.yaml"
        assert yaml_path.exists()

    def test_load_profile_from_yaml_roundtrips(self):
        from pathlib import Path
        from prover.unified.profiles import load_profile_from_yaml
        repo = Path(__file__).resolve().parent.parent
        yaml_path = repo / "config" / "profiles" / "conjecture_driven.yaml"
        loaded = load_profile_from_yaml(str(yaml_path))
        original = get_profile("conjecture_driven")
        assert loaded.name == original.name
        assert set(loaded.tools) == set(original.tools)
        assert loaded.framing == original.framing
        assert loaded.max_turns == original.max_turns
