"""scripts/dump_profile_yamls.py — Generate config/profiles/*.yaml from PRESETS.

Run once to refresh the YAML templates in ``config/profiles/``. Each
template is the dataclass dump of the corresponding ``PRESETS[name]``,
with header comments that point users at the relevant Python
definition.

The generated files are valid, round-trippable inputs to
``load_profile_from_yaml`` — the test
``tests/test_v5_yaml_profile_templates.py`` pins this round-trip.
"""
from __future__ import annotations

import os
import sys
from dataclasses import asdict, fields

# Make the project importable when run from the repo root.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import yaml

from prover.unified.profiles import (
    PRESETS, Profile, ObservationPolicy, SearchConfig, StopCondition,
    ToolKit,
)


# Per-profile docstrings — short pointer prepended as a YAML comment.
HEADERS: dict[str, str] = {
    "whole_proof": (
        "# Whole-proof generation (DeepSeek-Prover / Kimina / Goedel).\n"
        "# One LLM call → one ``by …`` block, no tools, no repair loop.\n"
        "# Use ``--max-samples K`` for pass@K.\n"),
    "whole_proof_repair": (
        "# Whole-proof + compile-and-fix loop (project default).\n"
        "# Submit, see errors, fix, repeat — bounded by ``max_turns``.\n"),
    "dsp": (
        "# Draft-Sketch-Prove (zero-shot).\n"
        "# A→sketch / B→decompose / C→premise / D→prove / E→repair phases\n"
        "# encoded in the system prompt.\n"),
    "reprover": (
        "# ReProver — step-level + on-demand premise retrieval.\n"
        "# 30-turn budget, tactic-by-tactic, retriever called from the\n"
        "# tool layer rather than pre-injected.\n"),
    "leandojo": (
        "# LeanDojo — pure step-level proving with the Mathlib hammer.\n"
        "# 50-turn budget, tactic_apply / goal_inspect / lean_auto only.\n"),
    "heterogeneous": (
        "# AI4Math flagship — N parallel sub-profiles + broadcast bus.\n"
        "# Each direction explores under a different framing / tools /\n"
        "# turn budget; a shared BroadcastBus shares discoveries.\n"),
    "kimina_batch": (
        "# Kimina Lean Server — batch verify over the REST API.\n"
        "# Best for pass@K sweeps and RL roll-outs.\n"
        "# Requires ``--backend kimina`` to actually wire a server.\n"),
    "pantograph_dsp": (
        "# Pantograph — mvar coupling + drafting (DSP-native).\n"
        "# Best on multi-conjunct / case-split goals.\n"
        "# Requires ``--backend pantograph`` (pypantograph or binary).\n"),
    "lookeng_lemma": (
        "# LooKeng (Seed-Prover 1.5) — stateless REPL + running lemma context.\n"
        "# Best for long proofs (PutnamBench / FATE-X). ~40% I/O reduction\n"
        "# vs. ``LocalTransport`` on theorems with > 20 steps.\n"),
    "nfl_hybrid": (
        "# NFL-HR (Yao et al., EMNLP 2025) — NL/FL hybrid reasoning.\n"
        "# NL→FL existence-theorem bridge for problems specified in\n"
        "# natural language (NuminaMath-LEAN style).\n"),
    "best_first": (
        "# Best-first search — outer driver picks the highest-scoring leaf,\n"
        "# agent does single-tactic expansion. v4: search tree lands in\n"
        "# ``meta.search_tree`` of dialog.json.\n"),
    "mcts": (
        "# MCTS-UCB1 — driver does selection + backprop, agent does\n"
        "# expansion. v4: search DAG written to ``meta.search_tree``,\n"
        "# linear ``messages`` carries the solved/best path for SFT.\n"),
    "beam": (
        "# Beam search — keep top-W leaves per depth.\n"
        "# Search tree written to ``meta.search_tree``.\n"),
}


# Universal header reused for every file.
COMMON_HEADER = (
    "# AUTO-GENERATED by ``scripts/dump_profile_yamls.py`` from\n"
    "# ``prover.unified.profiles.PRESETS``. Edit this file freely —\n"
    "# the next regen will overwrite it, but tests pin round-trip\n"
    "# semantics so a hand-edit will not silently drift from the\n"
    "# Python preset.\n"
    "#\n"
    "# Load:\n"
    "#   from prover.unified import load_profile_from_yaml, register_profile\n"
    "#   register_profile(load_profile_from_yaml(\"config/profiles/{name}.yaml\"))\n"
    "#\n"
    "# Then ``--profile {name}`` becomes selectable on the CLI.\n"
    "#\n"
)


def profile_to_dict(p: Profile) -> dict:
    """Dataclass-aware serialization that converts ToolKit enums to
    their string values. ``asdict`` handles the rest."""
    d = asdict(p)
    d["tools"] = [t.value if isinstance(t, ToolKit) else t for t in p.tools]
    return d


def render(p: Profile) -> str:
    body = profile_to_dict(p)
    header = COMMON_HEADER.format(name=p.name)
    pointer = HEADERS.get(p.name, "")
    yaml_text = yaml.safe_dump(
        body, sort_keys=False, default_flow_style=False, allow_unicode=True)
    return header + pointer + "\n" + yaml_text


def main() -> int:
    out_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                           "..", "config", "profiles")
    out_dir = os.path.abspath(out_dir)
    os.makedirs(out_dir, exist_ok=True)

    written = 0
    for name in sorted(PRESETS):
        path = os.path.join(out_dir, f"{name}.yaml")
        with open(path, "w", encoding="utf-8") as f:
            f.write(render(PRESETS[name]))
        written += 1
    print(f"Wrote {written} profile YAML(s) to {out_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
